inherit_gem:
  rubocop-rock: defaults.yml

AllCops:
    TargetRubyVersion: "2.5"
    Exclude:
    - lib/autobuild/packages/genom.rb
    - vendor/**/*
    - pkg/**/*

Style/ClassVars:
    Enabled: false

Style/TrivialAccessors:
    IgnoreClassMethods: true

Naming/PredicateName:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/AccessModifierDeclarations:
    EnforcedStyle: inline

Naming/FileName:
    Exclude:
      - lib/autobuild/import/git-lfs.rb




Layout/ParameterAlignment:
    Enabled: false

Layout/DotPosition:
    Enabled: false

Layout/FirstParameterIndentation:
    Enabled: false

Layout/AssignmentIndentation:
    Enabled: false

Layout/IndentationWidth:
    Enabled: false

Layout/MultilineMethodCallBraceLayout:
    Enabled: false

Layout/MultilineMethodCallIndentation:
    Enabled: false

Lint/RescueException:
    Enabled: false

Metrics/AbcSize:
    Enabled: false

Metrics/BlockLength:
    Enabled: false

Metrics/ClassLength:
    Enabled: false

Metrics/CyclomaticComplexity:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

Metrics/PerceivedComplexity:
    Enabled: false

Style/ClassCheck:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/EmptyLiteral:
    Enabled: false

Style/GuardClause:
    Enabled: false

Style/HashSyntax:
    Enabled: false

Style/PerlBackrefs:
    Enabled: false

Style/StringLiterals:
    Enabled: false

Layout/HeredocIndentation:
    Enabled: false

Metrics/LineLength:
    Max: 90
    Exclude:
    - test/**/*

Style/StringConcatenation:
    Enabled: false

Style/StderrPuts:
    Enabled: false

Style/GlobalStdStream:
    Enabled: false

Style/OptionalBooleanParameter:
    Enabled: false